name: IPTV

on:
  schedule:
    - cron: '0 21 * * *'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install selenium requests futures eventlet

      - name: Run IPTV
        run: python ${{ github.workspace }}/IPTV.py
- name: 提交更改
run: |
git config --local user.email "gs004209@163.com"
git config --local user.name "lqp861027"
git add .
git commit *.txt -m "Add generated file"
git push -f
